name: Polynomal-rails

on: [push,pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.2
    - name: Setup gems
      run: |
        gem install bundler
        bundle install --jobs 4
    - name: Run Standard
      run: bundle exec standardrb
    - name: Run tests
      run: bundle exec rspec
