name: Polynomal-rails

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    name: Ruby ${{ matrix.ruby }}
    strategy:
      matrix:
        ruby: ["2.7", "2.6", "2.5"]

    steps:
    - uses: actions/checkout@v2

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}

    - uses: actions/cache@v2
      with:
        path: vendor/bundle
        key: ${{ runner.os }}-${{ matrix.ruby }}-gems-v2-${{ hashFiles('**/Gemfile.lock') }}
        restore-keys: |
          ${{ runner.os }}-${{ matrix.ruby }}-gems-v2-

    - name: Setup gems
      run: |
        gem install bundler
        # for Ruby <= 2.6 , details https://github.com/rubygems/rubygems/issues/3284
        gem update --system 3.0.8 && gem update --system
        bundle config path vendor/bundle
        bundle install --jobs 4
        bundle exec appraisal install

    - name: Run Standard
      run: bundle exec standardrb

    - name: Install gems
      run: bundle exec appraisal bundle

    - name: Run tests
      run: bundle exec appraisal rspec
